name: PR Validation

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f yarn.lock ]; then
            npm ci
          else
            npm install
          fi
      
      # Only run lint if script exists, otherwise suggest adding it
      - name: Check if lint script exists
        id: check_lint
        run: |
          if grep -q "\"lint\":" package.json; then
            echo "HAS_LINT=true" >> $GITHUB_OUTPUT
          else
            echo "HAS_LINT=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Lint code
        if: steps.check_lint.outputs.HAS_LINT == 'true'
        run: npm run lint
        
      - name: Suggest adding linting
        if: steps.check_lint.outputs.HAS_LINT == 'false'
        run: echo "Consider adding ESLint to your project with a 'lint' script in package.json for better code quality"
      
      - name: Build
        run: npm run build
      
      - name: Run tests
        run: npm test

  # Add a required check that this workflow must pass
  require-tests:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Tests must pass
        run: echo "All tests passed!"
